### ISSUE TITLE
Fava command PR: Please fix my typo

### ISSUE THREAD

**Issue by tecosaur** [beancount/beancount-mode#11]
Hello,

I've just noticed I made a typo in my PR (oops)
https://github.com/beancount/beancount-mode/blob/7a0ef01d1ff6f8c318af944131310ca06d4c65ff/beancount.el#L1068
If the dash that should be in `beancount-mode` could be added, that would be great :slightly_smiling_face: 

*I think this is a bit too minor to warrant a PR*

**Comment by dnicolodi** [comment]
I fixed the typo and made the code more emacs-lispy. Please check if it works as intended.

**Comment by tecosaur** [comment]
Thanks
