### ISSUE TITLE
No defface is closed in d560451fda486a5d7e59a3108c0c7924e8a969f6

### ISSUE THREAD

**Issue by gagbo** [beancount/beancount-mode#20]
The `defface` statements aren't closed in https://github.com/beancount/beancount-mode/commit/d560451fda486a5d7e59a3108c0c7924e8a969f6 , it triggers a variety of issues (starting with byte-compilation failing, but also probably errors when trying to load a beancount file)

**Comment by dnicolodi** [comment]
Should be fixed now.
