### ISSUE TITLE
Support complete with split accounts?

### ISSUE THREAD

**Issue by Spike-Leung** [beancount/beancount-mode#26]
Hi, I have split accounts into different files, such as `accounts/income.beancount`, `accounts/expenses.beancount`...

Then, I write transactions in `transactions/xxx.beancount`, however, I can't complete accounts name which defined under `accounts` directory

How can I get completion ？

I find a repository that support `beancount-accounts-files` custom variable , which can defined `A list of files to provide candidates for accounts completion.`

Maybe can support in this repo ?

 English is not my native language; please excuse typing errors.

**Comment by kenhuang-io** [comment]
Hi @Spike-Leung,

> I find a repository that support beancount-accounts-files custom variable

Are you referring to <https://github.com/cnsunyour/beancount.el>?

I extracted that functionality as an advice so we can still use this package.

Check it out in my blog post:
<https://whatacold.io/blog/2022-09-10-emacs-beancount-account-files/>

**Comment by Spike-Leung** [comment]
> Hi @Spike-Leung,
> 
> > I find a repository that support beancount-accounts-files custom variable
> 
> Are you referring to https://github.com/cnsunyour/beancount.el?
> 
> I extracted that functionality as an advice so we can still use this package.
> 
> Check it out in my blog post: https://whatacold.io/blog/2022-09-10-emacs-beancount-accout-files/

I have tried it, works fine, thank ~ cool~

**Comment by lionel-** [comment]
It would still be nice to have this integrated in beancount-mode.
