### ISSUE TITLE
Payees do not autocomplete

### ISSUE THREAD

**Issue by twrightsman** [beancount/beancount-mode#28]
As far as I can tell there is no completion for payees. I think this is a useful feature because it helps keep consistent naming with payees, which in turn helps with grouping expenses by payee string. I used it all the time with `vim-beancount`.

I'm not familiar with Elisp yet but I could try and implement this sometime.

**Comment by blais** [comment]
That would be fun indeed.

**Comment by blais** [comment]
I'll close this for now, since noone had time for a go at this (and there's ~infinity cool ideas possible).
