### ISSUE TITLE
Should beancount-mode derive from prog-mode?

### ISSUE THREAD

**Issue by lionel-** [beancount/beancount-mode#29]
So that user config for prog-modes is inherited in beancount files.

**Comment by dnicolodi** [comment]
What general configuration for prod-modes would be relevant for Beancount mode?

**Comment by lionel-** [comment]
For instance I activate diff-hl-mode via prog-mode-hook.

A mode for a text file like beancount should either inherit from text-mode or from prog-mode, instead of fundamental-mode. I think prog-mode is more appropriate given the nature of the file: no prose, comments, indentation. Just regarding comments and indentations, users might have specific keybindings pertaining to these tasks enabled via prog-mode, which currently aren't inherited in beancount files.

**Comment by dnicolodi** [comment]
I remember thinking about this and deciding that `fundamental-mode` was a better fit, but I forgot why. Looking at what `prog-mode` does, I don't see anything that can be harmful for `beancount-mode`. I'll switch.

**Comment by blais** [comment]
@monnier What are your thoughts on this?

**Comment by monnier** [comment]
> @monnier What are your thoughts on this?

No strong opinion, here.  "no prose, comments, indentation" does sound
like a good argument in favor of `prog-mode`, tho.


        Stefan
