### ISSUE TITLE
Padding accounts don't autocomplete

### ISSUE THREAD

**Issue by ranjeethmahankali** [beancount/beancount-mode#32]
The second account, i.e. padding is not autocompleted at the moment. I tested by adding the following lines to `beancount-completion-at-point` function, between the conditions corresponding to `;; timestamped directives followed by account` and `;; posting`:

```
         ;; pad directive followed by two accounts
         ((beancount-looking-at
           (concat "^" beancount-date-regexp
                   "\\s-+" (regexp-opt '("pad"))
                   "\\s-+\\([" beancount-account-chars "]*\\)"
                   "\\s-+\\([" beancount-account-chars "]*\\)") 2 pos)
          (setq beancount-accounts nil)
          (list (match-beginning 2) (match-end 2) #'beancount-account-completion-table))
```

This works as expected and autocompletes the padding account. But I am not familiar enough with the repo to fork / PR it myself. Thank you so much!

**Comment by ranjeethmahankali** [comment]
I know this is very minor, but it's slightly annoying nonetheless. But will this be merged? or closed? I happy to make changes to the PR.

**Comment by blais** [comment]
you got it

**Comment by ranjeethmahankali** [comment]
Thank you!
