### ISSUE TITLE
Flymake integration

### ISSUE THREAD

**Issue by akirak** [beancount/beancount-mode#37]
I have implemented a basic flymake support: [flymake-bean-check](https://github.com/akirak/flymake-bean-check).

If you wish, I will contribute the file to this repository or transfer the repository to your organization.

What option would you prefer?

**Comment by blais** [comment]
Fun! Thank you Komamura-san.
Do you think adding the new file to the root of the beancount-mode would be
sufficient?
I'm okay with that; if you prefer to transfer repo I'm okay with that too
(though given the size it's probably more sensible to add to beancount-mode
if you prefer that).

**Comment by akirak** [comment]
> adding the new file to the root of the beancount-mode

I think it's fine. The flymake backend doesn't depend on any third-party library, but the user requires Emacs 27.1 to use flymake. Iif `beancount-mode` assumes Emacs 27.1, the added library can be part of the package. Otherwise, you can ship it as a separate package.

I have created a PR #38. If you are fine with this, please feel free to merge it.
