### ISSUE TITLE
beancount.el Warning (initialization): An error occurred while loading

### ISSUE THREAD

**Issue by dnjkalnvfjdkln** [beancount/beancount-mode#6]
Hello,

Sorry to bother you, trying to install beancount-mode for my emacs file

I loaded and pasted the code from your website into the init file.
I placed the beancount.el file into a folder
When I try beancount mode:  Alt-x beancount-mode I get an error:
 (beancount-highlight-transaction-at-point): (void-function beancount-highlight-transaction-at-point)

When I open emacs:
Warning (initialization): An error occurred while loading `/home/family281/.emacs.d/init.el':
Symbol's value as variable is void: completion-category-default

Could you please assist me?  I am not computer savvy.
Thank You

**Comment by dnjkalnvfjdkln** [comment]
All keybindings do not work.  All are voided.

**Comment by dnicolodi** [comment]
`beancount.el` requires Emacs version 26 or later. See discussion on the mailing list https://groups.google.com/g/beancount/c/ukhEbTyVKAY
