### ISSUE TITLE
Is beancount.el setting up custom completion mode correctly?

### ISSUE THREAD

**Issue by dnicolodi** [beancount/beancount-mode#7]
It appends to `completion-category-defaults` which does not seem the right thing to do. However, I don't know the Emacs completion machinery well enough to say for sure.

**Comment by blais** [comment]
This was added in 2015:
https://github.com/emacs-mirror/emacs/commit/d2cf05d1bac19d8564d0806f515b9f40fe57f4df#diff-9266fdaa0e4b1c20f4fe4d4f9d9deffb50ae18dd7663131b2f2fa6bee84014cdR1

I would suggest perhaps we just insert a version check, or ignore.
We can't support too many old versions; up to you.

**Comment by dnicolodi** [comment]
Maybe I could have said it better: this is not about supporting older Emacs but about implementing custom completion in the right way. I haven't spent much time looking at it, but I am not sure that appending to `completion-category-defaults` is the right thing to do, there may be a better extension point. I just noted it here as a thing to check.

**Comment by monnier** [comment]
FWIW, it looks right to me
[ Then again, I'm probably to blame for that code.  :-)   ]

**Comment by blais** [comment]
Closing for cause of "monnier completion." 
(I'm not going to argue with an ex-maintainer of Emacs about the right way to do things.)
