### ISSUE TITLE
Error with dependency against thingatpt in Emacs 26

### ISSUE THREAD

**Issue by zacharyasmith** [beancount/beancount-mode#8]
On L847 of `beancount.el`, there is this line:

```elisp
(define-thing-chars beancount-link beancount-link-chars)
```

This command `define-thing-chars` is no longer part of thingatpt. I do not know what the correct one should be. I have commented it out with success but do not know what won't work because of it.

**Comment by blais** [comment]
Oh that's a bummer.
We just need to define a thing-at-point that detects links, and one for tags, and perhaps one for accounts too.

**Comment by dnicolodi** [comment]
`define-thing-chars` is a thing in Emacs 27.1, thus the problem may be that it was not part of Emacs 26, not that it went away. However, there is no mention of when it was introduced in the doc string. If we believe the Emacs git mirror on Github, it was introduced here https://github.com/emacs-mirror/emacs/commit/9dbdc0f00567d0cf2d165ef9704983bfb588146f which indeed may be post Emacs 26.

Unfortunately, bumping the minimum required Emacs version to 27 may be premature.

Anyhow, the matching provided by `define-thing-chars` may be a bit simplistic for detecting links, tags, and account names, ie the regular expression should maybe be a bit more complex. I'll have a look at this later.

**Comment by blais** [comment]
Let's just conditionally disable the feature pre-27.

**Comment by prabusw** [comment]
This the exact error message for this issue in GNU Emacs 26.3

Warning (initialization): An error occurred while loading ‘~/.emacs.d/init.el’:
Symbol's function definition is void: define-thing-chars

Error message when emacs is run with --debug-init option

Debugger entered--Lisp error: (void-function define-thing-chars)
  (define-thing-chars beancount-link beancount-link-chars)

Temp solution:
As the issue opener zacharyasmith, mentioned, commenting out the line as shown below removes the error message.
;(define-thing-chars beancount-link beancount-link-chars)

I've done the detailed write up, so that new emacs users can identify and get this issue fixed quickly..

**Comment by blais** [comment]
We can insert a conditional, disabling the feature

**Comment by dnicolodi** [comment]
I was looking at doing it this morning, but then I got sidetracked trying to understand how to use the `thingatpt` machinery to correctly identify Beancount links (right now `(thing-at-point 'beancount-link)` happily returns things that are not links) and I didn't have time to properly test my solution yet.

**Comment by dnicolodi** [comment]
@prabusw @zacharyasmith Can you please test the latest commit and see if it works with Emacs 26?

**Comment by prabusw** [comment]
Dear Daniele,
Yes the current beancount.el works without any error message. Thank you.

Is there any reason for not tagging the commits with some kind of
versioning like 0.0.1 or 0.1, until you want to use 1.x. This way reporting
issues and checking solutions will be easier.

Note: I'm not using the git tool, so i don't know if it already exists as
the webview does not show the version information.

Thank you.

Cheers,
Prabu

**Comment by dnicolodi** [comment]
If you need to refer to a particular version of `beancount.el` you can use the git commit (abbreviated) hash, `7785e88` for the current head. There aren't official releases of `beancount.el` thus tagging the commits does not make much sense and the development is slow enough that there is very seldom need for referring to specific versions of the code.
