### ISSUE TITLE
Wolud you like a PR to add a command to open fava?

### ISSUE THREAD

**Issue by tecosaur** [beancount/beancount-mode#9]
I have this in my config, and it would be no trouble to upstream it :slightly_smiling_face:.

See: https://tecosaur.github.io/emacs-config/config.html#beancount

**Comment by dnicolodi** [comment]
I don't feel the need for something like it, but I don't see why not. Please submit this as a PR. If you do, there are a couple of things that need to be changed: we should not enforce that the file name associated to the current buffer ends in `beancount` and we should not use `browse-url-xdg-open` as it Linux only but something more portable.

**Comment by tecosaur** [comment]
Sure, I'll submit a PR shortly :slightly_smiling_face:
